version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9.3
    working_directory: /go/src/github.com/project/repo
    steps:
      - setup_remote_docker:
          version: 17.11.0-ce
          docker_layer_caching: true
      - checkout
      - run:
          name: Build
          command: docker build -t  ${OWNER}/${IMAGE_NAME}:$CIRCLE_TAG .
      - run:
          name: Tag as Latest
          command: docker tag ${OWNER}/${IMAGE_NAME}:$CIRCLE_TAG ${OWNER}/${IMAGE_NAME}:latest
      - run:
          name: Docker Login
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: Push image to registory
          command: docker push ${OWNER}/${IMAGE_NAME}
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/