version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9.3
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - setup_remote_docker:
          version: 17.11.0-ce
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.11.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build AND PUSH
          command: |
            TAG=$CIRCLE_TAG
            docker build -t   ${OWNER}/${IMAGE_NAME}:$TAG .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push ${OWNER}/${IMAGE_NAME}:$TAG
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/