alias:
  default_env: &default_env
    docker:
      - image: circleci/golang:1.9.3
    working_directory: /go/src/github.com/project/repo
  setup_remote_docker: &setup_remote_docker
    version: 17.11.0-ce
    docker_layer_caching: true

version: 2
jobs:
  build:
    <<: *default_env
    steps:
      - setup_remote_docker: *setup_remote_docker
      - checkout
      - run:
          name: Build
          command: docker build -t ${OWNER}/${IMAGE_NAME}:latest .
      - run:
          name: Save image
          command: docker image save ${OWNER}/${IMAGE_NAME}:latest > ./docker-image.tar
      - persist_to_workspace:
          root: .
          paths:
            - ./docker-image.tar
  test:
    <<: *default_env
    steps:
      - setup_remote_docker: *setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: Load image from tar
          command: docker load -i ./docker-image.tar
      - run:
          name: Download container-structure-test
          command: |
            curl -LO https://storage.googleapis.com/container-structure-test/v0.1.3/container-structure-test \
            && chmod +x container-structure-test \
            && sudo mv container-structure-test /usr/local/bin/
      - run:
          name: structure-test
          command: structure-test -test.v -image ${OWNER}/${IMAGE_NAME}:latest image_test.yml
  push:
    <<: *default_env
    steps:
      - setup_remote_docker: *setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: Load image from tar
          command: docker load -i ./docker-image.tar
      - run:
          name: Tag to latest
          command: docker tag ${OWNER}/${IMAGE_NAME}:latest ${OWNER}/${IMAGE_NAME}:$CIRCLE_TAG
      - run:
          name: Docker Login
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: Push image to registory
          command: docker push ${OWNER}/${IMAGE_NAME}
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - push:
          requires:
            - build
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/