alias:
  default_env: &default_env
    docker:
      - image: circleci/golang:1.9.3
    working_directory: /go/src/github.com/project/repo
  setup_remote_docker: &setup_remote_docker
    version: 17.11.0-ce
    docker_layer_caching: true

version: 2
jobs:
  build:
    <<: *default_env
    steps:
      - setup_remote_docker: *setup_remote_docker
      - checkout
      - run:
          name: Build
          command: make docker-build
      - run:
          name: Save image
          command: make docker-save
      - persist_to_workspace:
          root: .
          paths:
            - ./makefile
            - ./docker-image.tar
            - ./container-structure-test.yaml
  test:
    <<: *default_env
    steps:
      - setup_remote_docker: *setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: Load image from tar
          command: make docker-load
      - run:
          name: Download container-structure-test
          command: |
            curl -LO https://storage.googleapis.com/container-structure-test/v0.1.3/container-structure-test \
            && chmod +x container-structure-test \
            && sudo mv container-structure-test /usr/local/bin/structure-test
      - run:
          name: structure-test
          command: make docker-test
  push:
    <<: *default_env
    steps:
      - setup_remote_docker: *setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: Load image from tar
          command: make docker-load
      - run:
          name: Tag to latest
          command: make docker-tag tag=$CIRCLE_TAG
      - run:
          name: Docker Login
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: Push image to registory
          command: make docker-push
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - push:
          requires:
            - build
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/