version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9.3
    working_directory: /go/src/github.com/project/repo
    steps:
      - setup_remote_docker:
          version: 17.03.0-ce
          docker_layer_caching: true
      - run:
          name: Build AND PUSH
          command: |
            docker build -t   ${OWNER}/${IMAGE_NAME}:$CIRCLE_TAG .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push ${OWNER}/${IMAGE_NAME}:$CIRCLE_TAG
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/